version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    image: ''
    command: bash -c "alembic upgrade head"
    environment:
      - ./configs/config.json:/etc/deploy/configs/config.json
  nginx:
    image: nginx:stable-alpine
    environment:
      - "TZ=Asia/Barnaul"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: always
volumes:
  pg_data: